import { getServerSession } from "next-auth";
import Link from "next/link";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogoutBtn";

export const metadata = {
  title: "Tykan Forum",
  description: "Generated by create next app",
  openGraph: {
    title: "Tykan Forum",
    url: "https://nextjs.org",
    images: [
      {
        url: "https://nextjs.org/og.png",
        width: 800,
        height: 600,
      },
    ],
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <body>
        <div className="navbar bg-sky-200 px-4 py-2 text-slate-900 justify-between flex">
          <div className="space-x-4 my-auto">
            <Link href="/" className="font-black">
              TykanForum
            </Link>
            <Link href="/list" className="">
              List
            </Link>
          </div>
          {session == null ? (
            <LoginBtn />
          ) : (
            <LogoutBtn name={session.user?.name} />
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
